### ISSUE TITLE
Install 1.9.0

### ISSUE THREAD

**Issue by axi92** [sanack/node-jq#174]
## Description
I cant get node-jq installed.
If it helps I already have jq via apt installed.
I tried to create a symlink for /usr/bin/jq into node_modules/node-jq/bin/jq but that was not working...

### Error Message & Stack Trace

```bash
$ npm i node-jq

> node-jq@1.9.0 postinstall /home/user/telegram/raftingbot/node_modules/node-jq
> npm run install-binary


> node-jq@1.9.0 install-binary /home/user/telegram/raftingbot/node_modules/node-jq
> node scripts/install-binary.js

Building jq from https://github.com/stedolan/jq/releases/download//jq-1.6/jq-1.6.tar.gz
{ Error: Command failed: /bin/sh -c autoreconf -fi
configure.ac:36: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:36: error: possibly undefined macro: AM_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1


    at Promise.all.then.arr (/home/user/telegram/raftingbot/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr:
   'configure.ac:36: warning: macro \'AM_PROG_LIBTOOL\' not found in library\nconfigure.ac:36: error: possibly undefined macro: AM_PROG_LIBTOOL\n      If this token and others are legitimate, please use m4_pattern_allow.\n      See the Autoconf documentation.\nautoreconf: /usr/bin/autoconf failed with exit status: 1\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c autoreconf -fi',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@1.9.0 install-binary: `node scripts/install-binary.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@1.9.0 install-binary script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-06-26T04_49_53_443Z-debug.log
npm WARN raftingbot@1.0.0 No description
npm WARN raftingbot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@1.9.0 postinstall: `npm run install-binary`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@1.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-06-26T04_49_53_685Z-debug.log
```
## Environment
nodejs version:
```bash
Node.js v10.16.0
linux 4.15.0-52-generic
```
npm version:
```bash
6.9.0
```
node-jq version:
```bash
cat: node_modules/node-jq/package.json: No such file or directory
```

**Comment by davesnx** [comment]
Seems that is a problem with the makefile of jq itself. There's nothing to do with node-jq at this point.

```
configure.ac:36: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:36: error: possibly undefined macro: AM_PROG_LIBTOOL
```

If you have installed jq already, you can use `$ export NODE_JQ_SKIP_INSTALL_BINARY=true` to skip the installation and would work.

**Comment by axi92** [comment]
```bash
sudo apt install libtool
```
and it worked
