### ISSUE TITLE
Problem running node-tap tests

### ISSUE THREAD

**Issue by jerrythomas** [sanack/node-jq#298]
## Description

When running tests that use `node-jq` I am getting the following error

### sample code
No issues when run with `node index.js`
```js
const jq = require('node-jq');

async function convert(){
  const data = {a: 10};
  try {
    let result = await jq.run(".",
                              JSON.stringify(data),
                              { input: 'string' , output: 'json'});
    return result;
  } catch (err) {
    t.error(err)
  }
}
convert().then((res) => {
  console.log(res);
  process.exit()
})
```

### Test Source
This however runs into an issue. 

```js
const { test } = require('tap');
const jq = require('node-jq');

test('test jq', async t => {
  t.plan(1)
  const data = {a: 10};
  try {
    let result = await jq.run(".",
                              JSON.stringify(data),
                              { input: 'string' , output: 'json'});
    t.same(data, result)
  } catch (err) {
    t.error(err)
  }
});
```

### Error Message & Stack Trace

```text
test: jq.spec.js test jq
  origin:
    at:
      line: 462
      column: 3
      file: fs.js
      function: Object.openSync
    stack: |
      node_modules/node-jq/lib/exec.js:26:43
      new Promise (<anonymous>)
      exec (node_modules/node-jq/lib/exec.js:20:10)
      node_modules/node-jq/lib/jq.js:27:24
    errno: -13
    syscall: open
    code: EACCES
    path: /Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/bin/jq
  found:
    !error
    name: Error
    message: "EACCES: permission denied, open
      '/Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/bin/jq'"
    stack: >-
      Error:
          at Object.openSync (fs.js:462:3)
          at Proxy.readFileSync (fs.js:364:35)
          at mungeShebang (/usr/local/lib/node_modules/tap/node_modules/spawn-wrap/index.js:252:20)
          at munge (/usr/local/lib/node_modules/tap/node_modules/spawn-wrap/index.js:328:5)
          at ChildProcess.wrappedSpawn [as spawn] (/usr/local/lib/node_modules/tap/node_modules/spawn-wrap/index.js:89:5)
          at Proxy.spawn (child_process.js:548:9)
          at /Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/lib/exec.js:26:43
          at new Promise (<anonymous>)
          at exec (/Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/lib/exec.js:20:10)
          at /Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/lib/jq.js:27:24
    errno: -13
    syscall: open
    code: EACCES
    path: /Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/bin/jq
  stack: |
    Test.<anonymous> (jq.spec.js:13:7)
```
## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm/yarn, and node-jq.

Run the following to get it quickly:
nodejs version:
```bash
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
```
```
Node.js v13.13.0
darwin 19.4.0
```
yarn version: 
```bash
yarn --version
```
```
1.22.4
```
npm version:
```bash
npm --version
```
```
6.14.4
```
node-jq version: 
```bash
cat node_modules/node-jq/package.json | grep "version"
```
```
"version": "1.11.0",
```

**Comment by davesnx** [comment]
Hey @jerrythomas,

I'm not available to create a replicate example of your error and debug it (I'm on my Phone), but It seems like node-tap doesn't have permissions over the binary jq. Can you try to give run access directly to node-jq? or jq?

Thanks for opening the issue with the template, that helps a lot.

I will come to you as soon as I got a reproducible project.

Thanks again!

**Comment by jerrythomas** [comment]
I uploaded a repo with the repro code. Problem is not with the executable. 

https://github.com/jerrythomas/issue-jq-tap-nyc

**Comment by davesnx** [comment]
It seems that have to do with nyc: https://github.com/tapjs/node-tap/issues/669
