### ISSUE TITLE
Error: spawn jq ENOENT

### ISSUE THREAD

**Issue by barl0g** [sanack/node-jq#321]
```bash
$ cat test.js
#!/usr/bin/env node

const jq = require('node-jq')

jq.run('.', { foo: 'bar' }, { input: 'json' }).then(console.log)
```

```bash
$ ./test.js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/user/opt/cor/node_modules/node-jq/bin/jq ENOENT                                                                 
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)                                                      
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)                                                                 
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)                                                             
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)                                                      
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)**
```

## Environment

nodejs version:
```bash
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v10.21.0
linux 4.12.14-lp151.28.59-default
```
npm version:
```bash
npm --version
6.14.4
```
node-jq version:
```bash
cat node_modules/node-jq/package.json | grep "version"
  "version": "1.11.1"
```

**Comment by davesnx** [comment]
node-jq support node LTS which is v12, so currently we don't support v10. Please upgrade your nodejs.

Thanks!

**Comment by barl0g** [comment]
It's the same with v12

```bash
./node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v12.18.3
linux 4.12.14-lp151.28.59-default
```

```bash
./node test.js
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/user/opt/node-v12.18.3-linux-x64/bin/node_modules/node-jq/bin/jq ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/user/opt/node-v12.18.3-linux-x64/bin/node_modules/node-jq/bin/jq',
  path: '/home/user/opt/node-v12.18.3-linux-x64/bin/node_modules/node-jq/bin/jq',
  spawnargs: [ '.' ]
}
```

**Comment by barl0g** [comment]
And v14.

```bash
./node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v14.8.0
linux 4.12.14-lp151.28.59-default

./node test.js
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/user/opt/node-v14.8.0-linux-x64/bin/node_modules/node-jq/bin/jq ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/user/opt/node-v14.8.0-linux-x64/bin/node_modules/node-jq/bin/jq',
  path: '/home/user/opt/node-v14.8.0-linux-x64/bin/node_modules/node-jq/bin/jq',
  spawnargs: [ '.' ]
}

```

**Comment by davesnx** [comment]
Hey @barl0g, I'm sorry I just saw the v10 and assumed that was the problem. I set up this repo to discard any compatibility issue with node versions or jq versions: https://github.com/davesnx/try-node-jq

The error of ENONT seems like the jq binary is missing under node_modules/node_jq/bin/
`Error: spawn /Users/davesnx/dev/playgrounds/try-node-jq/node_modules/node-jq/bin/jq ENOENT`

Could you check if it's there? or at least you have it installed globally?

**Comment by barl0g** [comment]
I don't have bin directory in node-jq

```
$ ls node_modules/node-jq/                                                  
docs  lib  LICENSE.md  package.json  README.md  scripts  src
```
I installed node-jq with

```
$ export NODE_JQ_SKIP_INSTALL_BINARY=true
$ npm install node-jq

```

because i had some broken dependencies.

What should I do?

**Comment by davesnx** [comment]
Try installing jq globally then or don't use the NODE_JQ_SKIP_INSTALL_BINARY flag.

**Comment by barl0g** [comment]
I have jq installed globally.

```
$ which jq
/usr/bin/jq

$ jq --version
jq-1.6

$ jq --version
jq-1.6
```

**Comment by davesnx** [comment]
Then the node script running node-jq should work, isn't it?
