### ISSUE TITLE
Array as input causes crash

### ISSUE THREAD

**Issue by qistoph** [sanack/node-jq#363]
## Description

Calling node-jq with JSON input and supplying an array causes a crash, even though jq supports arrays as input.

The error reported is:
**UnhandledPromiseRejectionWarning: ValidationError: "json object" must be of type object**

```
echo -ne '["asdf","test"]' | jq 
[
  "asdf",
  "test"
]
```

### Test Source

```js
const jq = require("node-jq");
data = ["asdf","test"]
jq.run(".", data, {"input": "json"}).then(console.log)
```

### Error Message & Stack Trace

```
(node:24852) UnhandledPromiseRejectionWarning: ValidationError: "json object" must be of type object
    at Object.exports.process (/home/mm/MagicMirror/modules/MMM-json/node_modules/@hapi/joi/lib/errors.js:183:16)
    at Object.internals.entry (/home/mm/MagicMirror/modules/MMM-json/node_modules/@hapi/joi/lib/validator.js:140:26)
    at Object.exports.entry (/home/mm/MagicMirror/modules/MMM-json/node_modules/@hapi/joi/lib/validator.js:26:30)
    at internals.Base.validate (/home/mm/MagicMirror/modules/MMM-json/node_modules/@hapi/joi/lib/base.js:532:26)
    at Object.internals.assert (/home/mm/MagicMirror/modules/MMM-json/node_modules/@hapi/joi/lib/index.js:221:27)
    at Object.attempt (/home/mm/MagicMirror/modules/MMM-json/node_modules/@hapi/joi/lib/index.js:107:26)
    at validateArguments (/home/mm/MagicMirror/modules/MMM-json/node_modules/node-jq/lib/command.js:42:31)
    at commandFactory (/home/mm/MagicMirror/modules/MMM-json/node_modules/node-jq/lib/command.js:63:16)
    at /home/mm/MagicMirror/modules/MMM-json/node_modules/node-jq/lib/jq.js:22:55
    at new Promise (<anonymous>)
(node:24852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Found a fix, working on a PR

**Comment by amitzig** [comment]
Has this been solved?
Running with 
```js
const filter = '.[]';
const options = { input: 'json', output: 'compact' };
const jsonInput = [{ a: 1 }, { a: 'b' }];
output = await jq.run(filter, jsonInput, options);
```
Crashes for me with: 
`message: '"json object" must be of type object'`

**Comment by mackermans** [comment]
@amitzig Looks like the fix was merged but the npm package wasn't automatically published. I triggered a new release yesterday, though unfortunately, it bumped the major version to `2.0.0`, which communicates more of a breaking change than it actually is.

Have a look at version `2.0.0`, and if it's still broken, please open a new issue.
