### ISSUE TITLE
Error: bumping node-jq 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by trasherdk** [sanack/node-jq#462]
When trying to get rid of those annoying deprecated warnings
```sh
npm WARN deprecated strip-eof@2.0.0: Renamed to `strip-final-newline` to better represent its functionality.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be pro
```
I decided to bump `node-jq` to see if that would do it.

```sh
$ npm i node-jq@^2.1.0
npm ERR! Invalid Version: ^6.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trasherdk/.npm/_logs/2021-12-15T08_19_02_078Z-debug-0.log
```

From the log-file:
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'node-jq@^2.1.0' ]
1 info using npm@8.3.0
2 info using node@v16.13.1
```
... All good until
```
381 silly placeDep node_modules/@semantic-release/npm fs-extra@10.0.0 OK for: @semantic-release/npm@8.0.3 want: ^10.0.0
382 silly placeDep ROOT nerf-dart@1.0.0 OK for: @semantic-release/npm@8.0.3 want: ^1.0.0
383 timing idealTree Completed in 3633ms
384 timing command:i Completed in 3653ms
385 verbose stack TypeError: Invalid Version: ^6.0.1
385 verbose stack     at new SemVer (/usr/lib/node_modules/npm/node_modules/semver/classes/semver.js:38:13)
385 verbose stack     at compare (/usr/lib/node_modules/npm/node_modules/semver/functions/compare.js:3:32)
385 verbose stack     at Object.gte (/usr/lib/node_modules/npm/node_modules/semver/functions/gte.js:2:30)
385 verbose stack     at CanPlaceDep.checkCanPlaceCurrent (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:173:51)
385 verbose stack     at CanPlaceDep.checkCanPlace (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:157:27)
385 verbose stack     at new CanPlaceDep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/can-place-dep.js:114:26)
385 verbose stack     at PlaceDep.place (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:121:19)
385 verbose stack     at new PlaceDep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:71:10)
385 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:949:31
385 verbose stack     at Array.map (<anonymous>)
386 verbose cwd /home/trasherdk/local/github/ts-kraken
387 verbose Linux 4.4.276
388 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "node-jq@^2.1.0"
389 verbose node v16.13.1
390 verbose npm  v8.3.0
391 error Invalid Version: ^6.0.1
392 verbose exit 1
393 timing npm Completed in 3830ms
394 verbose unfinished npm timer reify 1639556342248
395 verbose unfinished npm timer reify:loadTrees 1639556342264
396 verbose unfinished npm timer idealTree:buildDeps 1639556342508
397 verbose unfinished npm timer idealTree:node_modules/@semantic-release/npm 1639556345889
398 verbose code 1
399 error A complete log of this run can be found in:
399 error     /home/trasherdk/.npm/_logs/2021-12-15T08_19_02_078Z-debug-0.log
```
Full log: [debug-0.log.gz](https://github.com/sanack/node-jq/files/7717740/debug-0.log.gz)

It seems to be `semver` don't like the format of a version somewhere, but I haven't encountered this anywhere else.

**Comment by davesnx** [comment]
I'm able to instal node-jq with a specific version such as `npm i node-jq@2.1.0`. Haven't seen this error since it complains about ^6.0.1 and your installing ^2.0.1.

**Comment by trasherdk** [comment]
Well, it's not `node-jq` as such it's complaining about, but some deep dependency.

`node-jq@^2.0.0` does install without complaining.

The problem exists in https://github.com/trasherdk/ts-kraken/

Even this fail:
```sh
$ rm -fr node_modules/
$ npm i node-jq@2.1.0
npm ERR! Invalid Version: ^6.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trasherdk.npm/_logs/2021-12-17T05_39_37_254Z-debug-0.log
```

**Comment by davesnx** [comment]
```
→ $ rm -rf node_modules
→ $ npm i node-jq@2.1.0
npm WARN deprecated strip-eof@2.0.0: Renamed to `strip-final-newline` to better represent its functionality.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 491 packages, and audited 749 packages in 5s

46 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
→ $ npm why ts-kraken
npm ERR! No dependencies found matching ts-kraken
```

node-jq doesn't rely on ts-kraken as you can see. 

Please don't remove the ISSUE_TEMPLATE and provide a reproducible environment such as a repo or a codesandbox. Closing since doesn't seem any related with node-jq.

**Comment by trasherdk** [comment]
`node-jq` is a dependency of [ts-kraken](https://github.com/trasherdk/ts-kraken/).

`ts-kraken` is currently importing `node-jq 2.0.0` without problems.  
Trying to upgrade `node-jq` to `2.1.0` causes this problem.

And for `a reproducible environment such as a repo`, this is it:
```sh
$ npx degit git@github.com:trasherdk/ts-kraken.git ts-kraken-node-jq
> cloned trasherdk/ts-kraken#HEAD to ts-kraken-node-jq
$ cd ts-kraken-node-jq/
$ npm ci
$ npm run build
$ npm i node-jq@2.1.0
npm ERR! Invalid Version: ^6.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trasherdk/.npm/_logs/2021-12-18T03_29_40_323Z-debug-0.log
```

**Comment by trasherdk** [comment]
Okay. I found the culprit, and it's not related to `node-jq`.

In `package.json` of `ts-kraken` I found this thing
```
  "resolutions": {
    "normalize-url": "^6.0.1"
},
```
Booting that part solved the problem. Sorry for the noise :blush:
