### ISSUE TITLE
Support Custom Root Certificate Authority

### ISSUE THREAD

**Issue by cschroed-usgs** [sanack/node-jq#545]
## Description

Using node-jq fails during `npm install` when using it in corporate environments that use an [HTTPS Interception solution](https://www.secureworks.com/research/transitive-trust).

### Test Source

```
$> npm install
```

### Error Message & Stack Trace

```bash
**$ npm install

> node-jq@2.3.4 postinstall /home/cschroed/src/wuds/database/node_modules/node-jq
> npm run install-binary


> node-jq@2.3.4 install-binary /home/cschroed/src/wuds/database/node_modules/node-jq
> node scripts/install-binary.js

Downloading jq from https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
GotError [RequestError]: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/home/cschroed/src/wuds/database/node_modules/download/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/stedolan/jq/releases/download/jq-1.6/jq-linux64',
  protocol: 'https:',
  url: 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@2.3.4 install-binary: `node scripts/install-binary.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@2.3.4 install-binary script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cschroed/.npm/_logs/2022-11-08T23_16_32_789Z-debug.log
npm WARN database@ No repository field.
npm WARN database@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@2.3.4 postinstall: `npm run install-binary`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@2.3.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cschroed/.npm/_logs/2022-11-08T23_16_33_054Z-debug.log
**
```

## Environment

nodejs version:

Node.js v14.20.0

linux 5.15.0-48-generic

npm version:

6.14.17

node-jq version:

2.3.4

## Suggested Solution

Ensure that the HTTP client that downloads jq recognizes user-customized cert bundles as specified via the `NPM_CONFIG_CAFILE` env var and/or the `cafile` property of `.npmrc`.

**Comment by davesnx** [comment]
You should be able to skip this with `export NODE_JQ_SKIP_INSTALL_BINARY=true`

**Comment by davesnx** [comment]
We don't plan to implement features like this on install-binary
